### ISSUE TITLE
The "Naming is a process" series by @arlobelshee

### ISSUE THREAD

**Issue by mp-stefc** [sccommunity/sc-newsletter-issues#10]
This is a very exhaustive series about naming things in software:
http://arlobelshee.com/tag/naming-is-a-process/
It is a step-by-step guide for finding good names and (naturally) at the same time a text about good software design.

**Comment by alebaffa** [comment]
great! thank you @mp-stefc !

**Comment by alebaffa** [comment]
Published in Newsletterr 7.
