### ISSUE TITLE
Moving Parts Blog Series by Samir Talwar

### ISSUE THREAD

**Issue by DarrenC** [sccommunity/sc-newsletter-issues#11]
Link: http://monospacedmonologues.com/post/138268503035/moving-parts

Description:
A series of short articles exploring the differences between object oriented and functional programming.

Why I think it should be included:
It's an interesting series in which compares and contrasts the two approaches to programming and is interesting for those who might be trying to do both.

**Comment by alebaffa** [comment]
Thanks @DarrenC ! :+1:

**Comment by alebaffa** [comment]
published on Newsletter 7.
