### ISSUE TITLE
Ouside-In TDD Video Series by Sandro Mancuso

### ISSUE THREAD

**Issue by mp-stefc** [sccommunity/sc-newsletter-issues#12]
A three-part series, in which Sandro performs the Bank Kata as a screencast, showing his Outside-In TDD workflow: 
Part 1: 
https://www.youtube.com/watch?v=XHnuMjah6ps
Part 2: 
https://www.youtube.com/watch?v=gs0rqDdz3ko
Part 3: 
https://www.youtube.com/watch?v=R9OAt9AOrzI

**Comment by alebaffa** [comment]
Thank you @mp-stefc ! I will add it in the next newsletter.
