### ISSUE TITLE
An story about craftsmanship on XML parsing

### ISSUE THREAD

**Issue by juankysoriano** [sccommunity/sc-newsletter-issues#14]
In blog this post I describe the journey we took to deep dive, evaluate and craft XML parsing to learn and develop as a team. It is more a tale about software development than a technical article.

It is not about one particular technology, but it talks about particular technologies, it is about the journey to get to well crafted code.

https://www.novoda.com/blog/an-story-about-xml-parsing-on-android/

I hope you find it worth of a mention!

**Comment by alebaffa** [comment]
Thank you very much @juankysoriano ! I just read it and found it very interesting and inspiring. And congratulations for your great job :+1: .

**Comment by blundell** [comment]
:100:
