### ISSUE TITLE
RubyConf 2015 - How to Stop Hating your Test Suite by Justin Searls

### ISSUE THREAD

**Issue by CarlosMChica** [sccommunity/sc-newsletter-issues#15]
Nice talk about how to improve your test suites - https://www.youtube.com/watch?v=VD51AkG8EZw

**Comment by alebaffa** [comment]
Hey @cmc00022, this talk was actually already part of the [newsletter #1](http://eepurl.com/bGQmoT) ;)

**Comment by alebaffa** [comment]
I am closing the issue since it is a duplicate. Anyway, thank you!

**Comment by CarlosMChica** [comment]
Sorry about that, should have checked it first
