### ISSUE TITLE
Rails Conf 2013 The Magic Tricks of Testing by Sandi Metz

### ISSUE THREAD

**Issue by CarlosMChica** [sccommunity/sc-newsletter-issues#17]
Simply one of the best testing-related talks I've ever watched.

https://www.youtube.com/watch?v=URSWYvyc42Mbe

**Comment by alebaffa** [comment]
Great, thank you @cmc00022 !

**Comment by alebaffa** [comment]
@cmc00022 FYI, I opened an issue #18 to myself for an improvement. I will work on it as soon as I can! Btw, thank you very much for your support. Really appreciate it!

**Comment by CarlosMChica** [comment]
My pleasure! I'm more than happy to collaborate with the community through your newsletter
