### ISSUE TITLE
DDDEurope - Tackling Complexity in the Heart of Software

### ISSUE THREAD

**Issue by CarlosMChica** [sccommunity/sc-newsletter-issues#22]
Eric Evans — Tackling Complexity in the Heart of Software:

http://dddeurop e.com/2016/eric-evans.html

**Comment by alebaffa** [comment]
Added to newsletter-10 :+1: Thanks!
@CarlosMChica do not forget to also write the reason why you think it is worth sharing it. This way I can add it directly in the abstract of the article in the newsletter (a new thing I'm going to add for the next issues).
